apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: hello-world-aoa
  project: default
  source:
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    chart: hello-world
    helm:
      releaseName: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
