apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: 'default'
  source:
    repoURL: https://github.com/jault3/argo-manifests.git
    targetRevision: main
    path: 'app-of-apps/cluster-test/'
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: false
