apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tool-specific-yaml
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        directories:
          - path: tool-specific-yaml/test/*/*/*
        repoURL: https://github.com/jault3/argo-manifests.git
        revision: main
  template:
    metadata:
      name: '{{.path.basename}}-{{index .path.segments 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jault3/argo-manifests.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        name: '{{index .path.segments 2}}'
        namespace: '{{index .path.segments 3}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
